USE e_commerce;

insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (1, 'Kuí', 'Véronique', 'rmaydwell0@tripod.com', '30747 Wayridge Court', 'Campos do Jordão', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (2, 'Mégane', 'Géraldine', 'fleipold1@paginegialle.it', '1 Ridge Oak Hill', 'Daxindian', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (3, 'Joséphine', 'Fèi', 'nbulcock2@businessweek.com', '52153 Armistice Trail', 'Cambanugoy', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (4, 'Mégane', 'Táng', 'umyner3@chicagotribune.com', '16107 Hazelcrest Terrace', 'La Guata', 'Honduras');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (5, 'Amélie', 'Maëly', 'rhaig4@clickbank.net', '7 Florence Park', 'Daiyue', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (6, 'Méng', 'Aí', 'sredsell5@prweb.com', '7380 Welch Crossing', 'Mitsukaidō', 'Japan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (7, 'Bénédicte', 'Måns', 'ddudbridge6@joomla.org', '21629 Dapin Junction', 'Alicia', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (8, 'Zoé', 'Yénora', 'ablouet7@people.com.cn', '50 Jana Terrace', 'Cardal', 'Uruguay');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (9, 'Lucrèce', 'Lèi', 'dtackett8@timesonline.co.uk', '6 Artisan Center', 'Molave', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (10, 'Åslög', 'Réservés', 'fconnock9@newsvine.com', '6300 Park Meadow Lane', 'Almirante Tamandaré', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (11, 'Lucrèce', 'Pélagie', 'tbrookhousea@ustream.tv', '4 Shasta Place', 'Limbuhan', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (12, 'Dorothée', 'Méng', 'ddanielskyb@latimes.com', '5277 Jenifer Center', 'Baghlān', 'Afghanistan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (13, 'Léane', 'Daphnée', 'gmckinnonc@nbcnews.com', '863 Arkansas Terrace', 'Puńsk', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (14, 'Maïly', 'Mén', 'nvannid@disqus.com', '51 Basil Road', 'Jõgeva', 'Estonia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (15, 'Görel', 'Marylène', 'tgunninge@washingtonpost.com', '0894 Old Shore Way', 'Riyom', 'Nigeria');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (16, 'Séverine', 'Eliès', 'pbrosolif@pinterest.com', '4 Vernon Park', 'Palmira', 'Colombia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (17, 'Yú', 'Lorène', 'nmatyushonokg@huffingtonpost.com', '600 Maple Place', 'Połaniec', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (18, 'Annotée', 'Réservés', 'dfairhallh@intel.com', '474 Aberg Court', 'Donskoy', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (19, 'Méline', 'Lorène', 'dmakepeacei@mapy.cz', '7166 Riverside Point', 'Sacramento', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (20, 'Cunégonde', 'Eloïse', 'cswiffinj@discovery.com', '44 Stephen Point', 'Vatutine', 'Ukraine');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (21, 'Andréa', 'Ruì', 'mkitchensidek@huffingtonpost.com', '77 Chive Lane', 'Beau Vallon', 'Seychelles');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (22, 'Eléa', 'Méghane', 'ghegdenl@google.pl', '43010 Randy Street', 'Sri Jayewardenepura Kotte', 'Sri Lanka');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (23, 'Alizée', 'Personnalisée', 'cbrundillm@cbslocal.com', '7 Lakeland Lane', 'Huanggangshan', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (24, 'Erwéi', 'Miléna', 'hklaggemann@time.com', '1891 Pankratz Pass', 'Matiompong', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (25, 'Yénora', 'Björn', 'jruselino@eventbrite.com', '152 Elka Lane', 'Hongjiang', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (26, 'Bérengère', 'Marie-josée', 'bspendlovep@xinhuanet.com', '1762 Almo Way', 'Vista Hermosa', 'Panama');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (27, 'Michèle', 'Åslög', 'ksleggq@last.fm', '99871 Summer Ridge Street', 'Nuevo Chamelecón', 'Honduras');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (28, 'Zhì', 'Lóng', 'gdinapolir@house.gov', '31930 Vahlen Plaza', 'Norrköping', 'Sweden');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (29, 'Andréa', 'Maïlys', 'trenfields@elpais.com', '2075 Dovetail Point', 'Monguno', 'Nigeria');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (30, 'Océane', 'Frédérique', 'egrestyet@diigo.com', '940 American Drive', 'Vichadero', 'Uruguay');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (31, 'Frédérique', 'Renée', 'mdixceeu@infoseek.co.jp', '95 Bobwhite Drive', 'Sovetskiy', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (32, 'Adélie', 'Séverine', 'tmashrov@is.gd', '4 Talisman Parkway', 'Mandi Bahāuddīn', 'Pakistan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (33, 'Hélèna', 'Méthode', 'aoconnellw@163.com', '0 Lillian Road', 'Soufrière', 'Saint Lucia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (34, 'Fèi', 'Marie-ève', 'mhighmanx@who.int', '5 Jenifer Park', 'Starobachaty', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (35, 'Eliès', 'Almérinda', 'rnehlseny@studiopress.com', '439 Washington Street', 'Beishan', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (36, 'Méline', 'Miléna', 'iyegorovninz@nyu.edu', '0568 Corscot Junction', 'Ichinoseki', 'Japan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (37, 'Annotée', 'Ruì', 'cpentycross10@nyu.edu', '0479 Spaight Pass', 'North Little Rock', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (38, 'Thérèse', 'Mylène', 'mbetz11@marriott.com', '245 Graceland Street', 'Maqiu', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (39, 'Kévina', 'Agnès', 'bchinge12@alexa.com', '707 Oxford Junction', 'Chambray-lès-Tours', 'France');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (40, 'Judicaël', 'Crééz', 'kstranio13@mit.edu', '710 Randy Trail', 'Comillas Norte', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (41, 'Cinéma', 'Mélys', 'osodo14@com.com', '5307 Fremont Center', 'Nagornyy', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (42, 'Åslög', 'Táng', 'kmcneill15@salon.com', '590 Westerfield Point', 'Prokuplje', 'Serbia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (43, 'Cloé', 'Liè', 'wgrainge16@house.gov', '4 Northridge Crossing', 'Vila Franca das Naves', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (44, 'Noémie', 'Maïly', 'kmeryett17@imageshack.us', '43 Miller Plaza', 'Saint-Louis', 'Senegal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (45, 'Maëlyss', 'Crééz', 'lscholcroft18@github.io', '3 Judy Circle', 'Krasnyy Oktyabr’', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (46, 'Bérangère', 'Audréanne', 'kturbayne19@bigcartel.com', '4 Golf Court', 'Figueiredo', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (47, 'Nadège', 'Alizée', 'cleabeater1a@ed.gov', '222 Mccormick Center', 'Amieira do Tejo', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (48, 'Edmée', 'Félicie', 'streadgall1b@nba.com', '1 Riverside Park', 'Wailebe', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (49, 'Kuí', 'Séverine', 'dgriswaite1c@t-online.de', '5291 Moland Park', 'Boca Raton', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (50, 'Bérénice', 'Félicie', 'gseleway1d@blogs.com', '4 Loftsgordon Pass', 'Glubokiy', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (51, 'Mahélie', 'Danièle', 'sbloodworth1e@loc.gov', '3 Bay Circle', 'Xiaochuan', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (52, 'Kallisté', 'Béatrice', 'jkrzyzanowski1f@usa.gov', '88 La Follette Point', 'Guérande', 'France');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (53, 'Léandre', 'Célestine', 'mstrover1g@discuz.net', '389 Packers Drive', 'Khānaqāh', 'Afghanistan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (54, 'Fèi', 'Lài', 'witzkovwich1h@comsenz.com', '63961 Almo Crossing', 'Shkodër', 'Albania');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (55, 'Stévina', 'Léandre', 'bchampley1i@quantcast.com', '557 Delladonna Way', 'Cauayan', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (56, 'Miléna', 'Lyséa', 'mdarcey1j@va.gov', '5 Esch Trail', 'Benhong', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (57, 'Simplifiés', 'Personnalisée', 'eroubert1k@npr.org', '02742 Gina Avenue', 'Ziroudani', 'Comoros');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (58, 'Styrbjörn', 'Loïca', 'sskirling1l@purevolume.com', '773 Claremont Pass', 'Cinunjang', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (59, 'Léa', 'Håkan', 'ncrandon1m@google.com.br', '5353 Johnson Avenue', 'Sabaneta', 'Colombia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (60, 'Adélaïde', 'Maëlle', 'qnorris1n@nytimes.com', '4515 Golden Leaf Avenue', 'Oropós', 'Greece');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (61, 'Fèi', 'Aurélie', 'bpaaso1o@google.it', '324 Marcy Alley', 'Manfalūţ', 'Egypt');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (62, 'Thérèsa', 'Håkan', 'dkenwright1p@goo.gl', '77701 Sommers Terrace', 'Perho', 'Finland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (63, 'Måns', 'Clémentine', 'kaujouanet1q@sitemeter.com', '30 Meadow Vale Trail', 'Maceda', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (64, 'Personnalisée', 'Geneviève', 'tpaddington1r@gizmodo.com', '4019 Mcbride Pass', 'Cherepovets', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (65, 'Adélie', 'Zhì', 'hbenediktsson1s@ucsd.edu', '846 Tony Parkway', 'Frankfurt am Main', 'Germany');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (66, 'Réservés', 'Maëlla', 'nsandeland1t@google.pl', '97 Graedel Way', 'Cheongju-si', 'South Korea');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (67, 'Méryl', 'Adélie', 'bafield1u@yellowbook.com', '883 Oxford Point', 'Seka', 'Thailand');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (68, 'Maëlys', 'Laurène', 'obaskerfield1v@icio.us', '41345 Katie Alley', 'Balkh', 'Afghanistan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (69, 'Liè', 'Sòng', 'arowena1w@newsvine.com', '4 Vera Pass', 'Gagarin', 'Armenia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (70, 'Almérinda', 'Ráo', 'hnunan1x@illinois.edu', '1796 Jenna Terrace', 'Crauthem', 'Luxembourg');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (71, 'Andréa', 'Yè', 'mheino1y@youtube.com', '782 Riverside Trail', 'Tarariras', 'Uruguay');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (72, 'Maïlys', 'Gaïa', 'jjore1z@gnu.org', '0309 Atwood Circle', 'Ivanovskoye', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (73, 'Joséphine', 'Ruò', 'cmasdon20@time.com', '94407 Warrior Junction', 'Palaran', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (74, 'Björn', 'Andrée', 'abales21@linkedin.com', '0 Anderson Parkway', 'Sekondi-Takoradi', 'Ghana');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (75, 'Mélia', 'Noémie', 'astirley22@behance.net', '863 Larry Street', 'Āgaro', 'Ethiopia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (76, 'Måns', 'Lauréna', 'adietz23@bloomberg.com', '873 Russell Terrace', 'Ishige', 'Japan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (77, 'Géraldine', 'Anaëlle', 'tklimuk24@thetimes.co.uk', '43236 2nd Plaza', 'Lembang', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (78, 'Lèi', 'Magdalène', 'dcusiter25@com.com', '9 Stuart Court', 'Shihua', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (79, 'Lài', 'Sòng', 'cmangam26@ocn.ne.jp', '10 Hooker Trail', 'Gongnong', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (80, 'Eléa', 'Fèi', 'hfrizell27@bloglines.com', '7745 Upham Place', 'Staryy Cherek', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (81, 'Michèle', 'Vénus', 'kdevaen28@com.com', '67340 Tony Center', 'Chantilly', 'France');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (82, 'Loïs', 'Laurène', 'rgaskill29@creativecommons.org', '25 Badeau Crossing', 'Nikolina Gora', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (83, 'Torbjörn', 'Maï', 'sfarlham2a@mozilla.com', '29166 Rutledge Avenue', 'Xarsingma', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (84, 'Lèi', 'Béatrice', 'shaymes2b@ifeng.com', '68971 Manufacturers Place', 'Morelos', 'Mexico');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (85, 'Maëlys', 'Céline', 'obloyes2c@umn.edu', '1507 Darwin Drive', 'Sarāvān', 'Iran');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (86, 'Méghane', 'Esbjörn', 'wlinklater2d@surveymonkey.com', '29339 Russell Street', 'Sayansk', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (87, 'Mahélie', 'Agnès', 'llinklater2e@sogou.com', '579 Forster Drive', 'Qindu', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (88, 'Marie-françoise', 'Maïté', 'lchaffe2f@gov.uk', '51 Memorial Road', 'Horad Krychaw', 'Belarus');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (89, 'Kuí', 'Ráo', 'fmagister2g@biblegateway.com', '69 Vernon Circle', 'Balneário Camboriú', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (90, 'Bérangère', 'Laurélie', 'gsanches2h@reddit.com', '32930 Dixon Center', 'Sandaowan', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (91, 'Célestine', 'Méryl', 'aarkell2i@behance.net', '01423 Chinook Crossing', 'Cibiru', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (92, 'Lén', 'Eliès', 'kauguste2j@reddit.com', '04 Pond Point', 'Stockholm', 'Sweden');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (93, 'Adélie', 'Naéva', 'akunzel2k@house.gov', '90 Heath Plaza', 'Sempu', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (94, 'Vénus', 'Zoé', 'skinforth2l@macromedia.com', '7296 Shopko Alley', 'Radvanice', 'Czech Republic');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (95, 'Örjan', 'Loïc', 'btowey2m@dropbox.com', '903 Doe Crossing Junction', 'Tucaní', 'Venezuela');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (96, 'Maïlys', 'Yè', 'rspurdon2n@furl.net', '427 Loomis Plaza', 'Rinbung', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (97, 'Méthode', 'Fèi', 'jkochel2o@flavors.me', '99 Katie Circle', 'Boa Esperança', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (98, 'Andréanne', 'Pål', 'htarling2p@sfgate.com', '3705 Mesta Avenue', 'Laojunmiao', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (99, 'Salomé', 'Vérane', 'jhenrionot2q@feedburner.com', '8 Riverside Drive', 'Zhongshi', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (100, 'Fèi', 'Aí', 'icopnell2r@bizjournals.com', '18 Linden Avenue', 'Muzaffargarh', 'Pakistan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (101, 'Örjan', 'Nélie', 'kmccrystal2s@nps.gov', '83 South Alley', 'Pereira', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (102, 'Göran', 'Maïlys', 'kpawlowicz2t@yahoo.co.jp', '94 Roxbury Plaza', 'Saint Lucia', 'Malta');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (103, 'Loïca', 'Maëlys', 'grault2u@biglobe.ne.jp', '9024 Caliangt Plaza', 'Xiangyang', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (104, 'Lén', 'Camélia', 'kinsoll2v@cam.ac.uk', '0 Oxford Circle', 'Horizonte', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (105, 'Judicaël', 'Adèle', 'gdufaire2w@123-reg.co.uk', '30 Miller Road', 'Igboho', 'Nigeria');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (106, 'Adèle', 'Yóu', 'acalcraft2x@omniture.com', '946 Summer Ridge Drive', 'Ruteng', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (107, 'Hélène', 'Laurène', 'wwhitsun2y@paypal.com', '13175 Vahlen Way', 'Yanling', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (108, 'Athéna', 'Pål', 'apeck2z@nydailynews.com', '95 Mallory Avenue', 'Győr', 'Hungary');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (109, 'Ruò', 'Inès', 'abrunn30@altervista.org', '109 Charing Cross Hill', 'Nijemci', 'Croatia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (110, 'Pål', 'Pò', 'njelliman31@github.com', '4115 Saint Paul Place', 'Kamárai', 'Greece');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (111, 'Léandre', 'Salomé', 'sashelford32@thetimes.co.uk', '80 Fair Oaks Crossing', 'Boulogne-Billancourt', 'France');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (112, 'Naéva', 'André', 'dbowsher33@geocities.jp', '45 Del Sol Drive', 'Xiaohe', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (113, 'Maëly', 'Mà', 'dzanioletti34@omniture.com', '5860 Springview Way', 'Passos', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (114, 'Angèle', 'Loïca', 'nmenego35@dagondesign.com', '83 Basil Pass', 'Chía', 'Colombia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (115, 'Andréa', 'Cécile', 'awhellans36@bizjournals.com', '34305 8th Park', 'Xing’an', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (116, 'Gwenaëlle', 'André', 'kchastenet37@sohu.com', '9 Forest Road', 'San Francisco', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (117, 'Jú', 'Laïla', 'nwimpenny38@harvard.edu', '794 Oriole Point', 'Prengtale', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (118, 'Véronique', 'Géraldine', 'dsamwayes39@symantec.com', '77 Loftsgordon Point', 'Halamendu', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (119, 'Måns', 'Åke', 'texroll3a@marketwatch.com', '5231 Dayton Center', 'Funaishikawa', 'Japan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (120, 'Intéressant', 'Maï', 'ecotterrill3b@chron.com', '5 Havey Trail', 'Mölndal', 'Sweden');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (121, 'Mélia', 'Félicie', 'bbaison3c@soup.io', '8384 Harbort Avenue', 'Bromma', 'Sweden');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (122, 'Amélie', 'Clélia', 'cwilbore3d@digg.com', '412 Tomscot Place', 'Chicago', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (123, 'Estève', 'Cléa', 'rdomini3e@time.com', '1163 Columbus Street', 'Sukamanah', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (124, 'Estée', 'Kuí', 'vhenrie3f@163.com', '19 Scott Terrace', 'Vilarinho', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (125, 'Cinéma', 'Eugénie', 'cflynn3g@washington.edu', '5 Hoepker Street', 'Mayisad', 'Haiti');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (126, 'Thérèsa', 'Valérie', 'bineson3h@sphinn.com', '327 La Follette Trail', 'Neópolis', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (127, 'Célestine', 'Mélissandre', 'rioannou3i@shinystat.com', '1074 Iowa Way', 'Lages', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (128, 'Erwéi', 'Léana', 'mjacquot3j@wunderground.com', '03371 Schiller Center', 'Sumuranyar', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (129, 'Eliès', 'Thérèsa', 'oderrington3k@bbb.org', '63522 Heffernan Drive', 'Sayang Lauq', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (130, 'Marie-thérèse', 'Zoé', 'gmackriell3l@spotify.com', '05 Derek Center', 'Ljungby', 'Sweden');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (131, 'Marylène', 'Marie-ève', 'emilham3m@1und1.de', '7839 Barnett Junction', 'Lahuaytambo', 'Peru');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (132, 'Gaïa', 'Clémentine', 'aaartsen3n@nbcnews.com', '87990 Chive Alley', 'Anbyŏn-ŭp', 'North Korea');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (133, 'Simplifiés', 'Marie-hélène', 'lfernley3o@biglobe.ne.jp', '401 Glacier Hill Road', 'Domaniewice', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (134, 'Annotés', 'Yáo', 'alyvon3p@qq.com', '9 Weeping Birch Way', 'Miedzichowo', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (135, 'Maëly', 'Nélie', 'pbaxendale3q@nbcnews.com', '52 Oriole Place', 'Liuzhi', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (136, 'Miléna', 'Noëlla', 'xcragoe3r@google.nl', '15803 Iowa Court', 'Huanghuatan', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (137, 'Marylène', 'Marylène', 'dramard3s@hatena.ne.jp', '27 Oakridge Way', 'Orly', 'France');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (138, 'Amélie', 'Wá', 'mworsfield3t@usatoday.com', '8604 Alpine Place', 'Brudzeń Duży', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (139, 'Uò', 'Régine', 'ewyke3u@mlb.com', '698 Schurz Court', 'Sanhe', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (140, 'Léonie', 'Noémie', 'scogswell3v@w3.org', '8 Red Cloud Court', 'Benito Juarez', 'Mexico');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (141, 'Hélène', 'Léana', 'gcullingworth3w@arstechnica.com', '14587 Hallows Street', 'Wiwilí', 'Nicaragua');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (142, 'Håkan', 'Loïs', 'edevita3x@shutterfly.com', '499 Basil Circle', 'Prozor', 'Bosnia and Herzegovina');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (143, 'Åke', 'Aí', 'sheyburn3y@omniture.com', '07123 Northwestern Circle', 'An Naşşārīyah', 'Palestinian Territory');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (144, 'Cléa', 'Inès', 'eslimings3z@twitter.com', '64306 Elka Center', 'Incheon', 'South Korea');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (145, 'Françoise', 'Daphnée', 'acranch40@examiner.com', '50 Cottonwood Pass', 'Byera Village', 'Saint Vincent and the Grenadines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (146, 'Yáo', 'Miléna', 'slaurenzi41@unesco.org', '736 Randy Point', 'Rakvere', 'Estonia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (147, 'Eléonore', 'Gösta', 'swarriner42@illinois.edu', '67 Artisan Terrace', 'Kadubincarung', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (148, 'Eliès', 'Néhémie', 'kkubach43@nbcnews.com', '8 Moulton Point', 'Yermish’', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (149, 'Cléopatre', 'Wá', 'leggins44@youtu.be', '898 Graedel Avenue', 'Cibungur', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (150, 'Zhì', 'Adélie', 'fmckeating45@nifty.com', '82 Burning Wood Road', 'Dayu', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (151, 'Hélène', 'Illustrée', 'nfishpool46@hhs.gov', '17 Mifflin Plaza', 'Vizal San Pablo', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (152, 'Audréanne', 'Lóng', 'kmorphet47@typepad.com', '92130 Straubel Trail', 'Lakeland', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (153, 'Maïly', 'Véronique', 'vtreweke48@fotki.com', '2430 Donald Pass', 'Svrljig', 'Serbia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (154, 'Léonie', 'Mélia', 'gmacrae49@army.mil', '642 Kensington Pass', 'Pawłosiów', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (155, 'Dù', 'Noémie', 'sredpath4a@plala.or.jp', '28 Talmadge Terrace', 'Yangdian', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (156, 'Cécile', 'Océane', 'dfranca4b@pagesperso-orange.fr', '91200 Fallview Circle', 'Vicente Guerrero', 'Mexico');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (157, 'Pénélope', 'Laïla', 'egraver4c@huffingtonpost.com', '1933 Miller Pass', 'Colonia Nicolich', 'Uruguay');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (158, 'Sòng', 'Publicité', 'lbettanay4d@bizjournals.com', '9980 Arkansas Road', 'Wąbrzeźno', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (159, 'Åslög', 'Cunégonde', 'sgillicuddy4e@home.pl', '888 Columbus Point', 'Iłowo -Osada', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (160, 'Maëly', 'Dù', 'wandrelli4f@hud.gov', '95773 Gina Point', 'Shuozhou', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (161, 'Lài', 'Loïc', 'ideere4g@technorati.com', '56319 Claremont Pass', 'Koroška Bela', 'Slovenia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (162, 'Réservés', 'Océanne', 'keisikowitz4h@mac.com', '21 Mccormick Hill', 'Olszówka', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (163, 'Maïly', 'Marie-françoise', 'emcreynolds4i@microsoft.com', '55122 Maryland Terrace', 'Songmuping', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (164, 'Bérengère', 'Anaëlle', 'jfishley4j@rakuten.co.jp', '4533 5th Crossing', 'Paniqui', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (165, 'Méryl', 'Gösta', 'mkingwell4k@comcast.net', '016 Iowa Pass', 'Bacalan', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (166, 'Mén', 'Tú', 'gguillem4l@posterous.com', '3137 Kingsford Road', 'Pärnu', 'Estonia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (167, 'Simplifiés', 'Océane', 'pseeborne4m@eventbrite.com', '216 Dapin Road', 'Sacanta', 'Argentina');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (168, 'Kévina', 'Märta', 'aaugur4n@rambler.ru', '13 Coolidge Center', 'Tyumen', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (169, 'Irène', 'Céline', 'rcarvell4o@reverbnation.com', '5 3rd Trail', 'Néa Éfesos', 'Greece');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (170, 'Cléa', 'Régine', 'dtejada4p@freewebs.com', '8706 Eastlawn Trail', 'Kubangkondang', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (171, 'Lèi', 'Marie-josée', 'nellington4q@sciencedaily.com', '2 Clyde Gallagher Pass', 'Sandefjord', 'Norway');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (172, 'Åslög', 'Edmée', 'gharold4r@printfriendly.com', '2092 Blaine Place', 'Všemina', 'Czech Republic');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (173, 'Maëlann', 'Eliès', 'emuschette4s@123-reg.co.uk', '57536 Welch Drive', 'Vaggeryd', 'Sweden');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (174, 'Lyséa', 'Gérald', 'bwalkinshaw4t@tripod.com', '729 Dawn Lane', 'Xiangzikou', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (175, 'Néhémie', 'Célia', 'fcroisdall4u@amazon.de', '0540 Elgar Pass', 'Werasari', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (176, 'Thérèse', 'Åke', 'ykeeley4v@mac.com', '4257 Weeping Birch Circle', 'Gaotang', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (177, 'Léonore', 'Cécile', 'imaddrah4w@craigslist.org', '69 Mallory Alley', 'Cervantes', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (178, 'Félicie', 'Renée', 'bsummerell4x@smugmug.com', '93 Mockingbird Place', 'Uddiawan', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (179, 'Åke', 'Bérangère', 'rdevenport4y@washingtonpost.com', '6 Surrey Center', 'Miechów Charsznica', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (180, 'Åsa', 'Liè', 'kfoad4z@elpais.com', '090 Warrior Center', 'Trakan Phut Phon', 'Thailand');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (181, 'Andrée', 'Cécilia', 'rbabbs50@altervista.org', '7 Ruskin Road', 'Paraipaba', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (182, 'Mahélie', 'Inès', 'flapham51@infoseek.co.jp', '6 Scoville Road', 'Halmstad', 'Sweden');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (183, 'Mélinda', 'Marie-noël', 'omistry52@ebay.com', '24325 Esch Parkway', 'Milíkov', 'Czech Republic');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (184, 'Léane', 'Märta', 'ahulme53@discovery.com', '727 Grayhawk Alley', 'Zhaoxian', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (185, 'Bénédicte', 'Audréanne', 'ssimonutti54@nationalgeographic.com', '808 Mallory Parkway', 'Bélabo', 'Cameroon');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (186, 'Eléonore', 'Françoise', 'mpendreigh55@nyu.edu', '2022 Ilene Lane', 'Santo Domingo Oeste', 'Dominican Republic');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (187, 'Gwenaëlle', 'Nélie', 'cshinner56@miibeian.gov.cn', '6039 Morrow Road', 'Gurung', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (188, 'Märta', 'Wá', 'qswait57@nsw.gov.au', '9610 Maywood Parkway', 'Tomé', 'Chile');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (189, 'Ophélie', 'Kallisté', 'bmackie58@unc.edu', '38 Victoria Road', 'Lekas', 'Albania');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (190, 'Annotés', 'Lài', 'mlismer59@cbsnews.com', '6 Florence Place', 'Atlanta', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (191, 'Illustrée', 'Gaëlle', 'lcarnow5a@usda.gov', '239 Transport Way', 'Salvacion', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (192, 'Valérie', 'Françoise', 'sedgerton5b@meetup.com', '8237 Brentwood Pass', 'Dimitsána', 'Greece');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (193, 'Léone', 'Garçon', 'tliversage5c@trellian.com', '050 Elgar Drive', 'Sukarame', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (194, 'Léana', 'Lyséa', 'cmapledorum5d@t.co', '6911 Cardinal Plaza', 'Tibati', 'Cameroon');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (195, 'Kù', 'Marie-françoise', 'dshuttleworth5e@slideshare.net', '96722 Heffernan Hill', 'Morani', 'Macedonia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (196, 'Salomé', 'Béatrice', 'sbliven5f@pinterest.com', '5854 Warner Lane', 'Glamoč', 'Bosnia and Herzegovina');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (197, 'Märta', 'Ráo', 'ddickey5g@altervista.org', '74 Dottie Avenue', 'Ratoath', 'Ireland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (198, 'Miléna', 'Simplifiés', 'dwinnister5h@google.co.uk', '22439 Parkside Parkway', 'Puerto Cisnes', 'Chile');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (199, 'Mélinda', 'Mahélie', 'afrodsam5i@elpais.com', '6 Maple Lane', 'Degeberga', 'Sweden');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (200, 'Anaël', 'Clémence', 'creimer5j@is.gd', '742 Tennessee Point', 'Cottbus', 'Germany');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (201, 'Inès', 'Lèi', 'cgatchell5k@prlog.org', '5863 Green Ridge Lane', 'Sungaipuntik', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (202, 'Torbjörn', 'Méline', 'bcowper5l@nymag.com', '6 Mcbride Circle', 'Lucerna', 'Honduras');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (203, 'Kallisté', 'Réjane', 'rkettlesing5m@princeton.edu', '242 Heath Park', 'Santa Lucía', 'Honduras');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (204, 'Maëline', 'Médiamass', 'hgorgl5n@uiuc.edu', '4 Riverside Center', 'Maopingchang', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (205, 'Publicité', 'Tú', 'fmenat5o@mozilla.org', '771 Golf View Terrace', 'Pandanwangi', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (206, 'Mylène', 'Mélissandre', 'hdaviddi5p@slideshare.net', '0 Coleman Point', 'Skawica', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (207, 'Magdalène', 'Méghane', 'bpaur5q@t-online.de', '4 Comanche Center', 'Petare', 'Venezuela');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (208, 'Angélique', 'Camélia', 'gchildren5r@icio.us', '486 Bay Way', 'Arcos de Valdevez', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (209, 'Danièle', 'Léonie', 'fstanbrooke5s@last.fm', '8734 Mariners Cove Way', 'Nové Město nad Metují', 'Czech Republic');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (210, 'Michèle', 'Océanne', 'jellissen5t@google.com', '79 Harbort Court', 'Kranuan', 'Thailand');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (211, 'Marylène', 'Mahélie', 'tgronowe5u@usa.gov', '2027 8th Trail', 'Nyachera', 'Uganda');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (212, 'Anaïs', 'Agnès', 'acorderoy5v@reddit.com', '84441 Fremont Crossing', 'Dumalneg', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (213, 'Fèi', 'Maï', 'dbottoms5w@seattletimes.com', '794 Rusk Court', 'Christchurch', 'New Zealand');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (214, 'Örjan', 'Pélagie', 'papplewhite5x@nsw.gov.au', '6844 7th Street', 'Melun', 'France');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (215, 'Célia', 'Kuí', 'hmcfayden5y@digg.com', '7 Pawling Center', 'Kayangel', 'Palau');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (216, 'Cinéma', 'Célia', 'trhoddie5z@cloudflare.com', '96 Mayer Road', 'Namerikawa', 'Japan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (217, 'Naéva', 'Maëlle', 'csergant60@quantcast.com', '56673 Steensland Avenue', 'Bulung’ur', 'Uzbekistan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (218, 'Gisèle', 'Lén', 'lkingsford61@time.com', '14910 Mcbride Hill', 'Vysehrad', 'Czech Republic');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (219, 'Cloé', 'Lorène', 'tfarquar62@digg.com', '31 Evergreen Hill', 'Ngampon', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (220, 'Maëline', 'Clélia', 'awhittock63@npr.org', '25 Becker Parkway', 'Kulase', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (221, 'Pål', 'Renée', 'elongshaw64@unicef.org', '08136 Larry Plaza', 'Jiangkou', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (222, 'Eliès', 'Angélique', 'cmaher65@people.com.cn', '01 Elgar Trail', 'Guayabal', 'Venezuela');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (223, 'Solène', 'Annotée', 'nharbord66@discuz.net', '04199 Miller Hill', 'Vale de Madeiros', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (224, 'Léonore', 'Méline', 'smcbain67@tripadvisor.com', '6489 Reindahl Crossing', 'Basel', 'Switzerland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (225, 'Táng', 'Simplifiés', 'fllorens68@thetimes.co.uk', '925 Toban Road', 'Pancheng', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (226, 'Léana', 'Marie-thérèse', 'obandy69@marriott.com', '9 Nevada Crossing', 'Laboulaye', 'Argentina');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (227, 'Mélinda', 'Amélie', 'emcquode6a@vimeo.com', '61915 Tennyson Street', 'Fès', 'Morocco');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (228, 'Garçon', 'Nadège', 'kbodicam6b@washington.edu', '3068 Burning Wood Way', 'Gwoźnica Górna', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (229, 'Maëlann', 'Léa', 'lcouldwell6c@hibu.com', '7470 Sunfield Plaza', 'Oklahoma City', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (230, 'Lóng', 'Dafnée', 'mstuart6d@pagesperso-orange.fr', '9 Golf Road', 'Strassen', 'Luxembourg');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (231, 'Eléonore', 'Mégane', 'mkirimaa6e@51.la', '567 Badeau Way', 'Lamadelaine', 'Luxembourg');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (232, 'Gisèle', 'Garçon', 'rteal6f@weather.com', '65 Northland Hill', 'Jingshan', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (233, 'Adèle', 'Pò', 'amatveichev6g@yellowpages.com', '74450 Lighthouse Bay Plaza', 'Cherbourg-Octeville', 'France');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (234, 'Yóu', 'Méghane', 'ftschirasche6h@ifeng.com', '5 Claremont Point', 'Saint Louis', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (235, 'Adèle', 'Eliès', 'jflanigan6i@va.gov', '7 Summerview Crossing', 'Wugui', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (236, 'Léa', 'Yú', 'rgrigorushkin6j@hp.com', '6036 Hoffman Lane', 'Hội An', 'Vietnam');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (237, 'Céline', 'Lucrèce', 'dcrosio6k@time.com', '87140 Sunnyside Alley', 'Yamoussoukro', 'Ivory Coast');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (238, 'Maëlyss', 'Vérane', 'chuison6l@free.fr', '958 Kensington Drive', 'Kumba', 'Cameroon');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (239, 'Loïca', 'Méryl', 'mtarbox6m@deviantart.com', '833 Del Mar Terrace', 'Besançon', 'France');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (240, 'Marie-hélène', 'Hélène', 'dempringham6n@amazon.co.jp', '8 Hintze Court', 'Girardot', 'Colombia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (241, 'Almérinda', 'Clémence', 'mgrinnov6o@dagondesign.com', '40 Hagan Avenue', 'Bacong', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (242, 'Eloïse', 'Néhémie', 'nforcade6p@marriott.com', '26966 Merchant Hill', 'Aqtoghay', 'Kazakhstan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (243, 'Aloïs', 'Kuí', 'bgoranov6q@unc.edu', '7 Jackson Alley', 'Ufimskiy', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (244, 'Miléna', 'Illustrée', 'mhuortic6r@cdc.gov', '1003 Amoth Park', 'Chaiyaphum', 'Thailand');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (245, 'Geneviève', 'Cléa', 'cfensome6s@cyberchimps.com', '33187 Eliot Crossing', 'La Paz Centro', 'Nicaragua');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (246, 'Stéphanie', 'Åsa', 'mmaccole6t@cocolog-nifty.com', '105 Lindbergh Point', 'Salgueiro', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (247, 'Liè', 'Fèi', 'pmessom6u@ucla.edu', '22993 Mcguire Place', 'Ukhta', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (248, 'Aí', 'Faîtes', 'ccona6v@liveinternet.ru', '522 Shopko Park', 'Di Linh', 'Vietnam');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (249, 'Camélia', 'Marie-thérèse', 'jmillom6w@walmart.com', '96044 Eastlawn Terrace', 'Dioknisi', 'Georgia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (250, 'Nadège', 'Michèle', 'abromhead6x@alibaba.com', '2 Carey Street', 'Čajniče', 'Bosnia and Herzegovina');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (251, 'Pål', 'Thérèsa', 'bpapachristophorou6y@bizjournals.com', '3908 Kedzie Hill', 'Trondheim', 'Norway');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (252, 'Almérinda', 'Wá', 'nninnis6z@fema.gov', '44026 Rutledge Trail', 'Bonga', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (253, 'Hélèna', 'Mélanie', 'ccadany70@google.de', '9162 Russell Way', 'Göteborg', 'Sweden');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (254, 'Maéna', 'Gisèle', 'hfairlie71@gravatar.com', '8567 Gateway Road', 'Xipu', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (255, 'Naëlle', 'Tán', 'lscoggan72@prweb.com', '659 Waxwing Alley', 'Jiachuan', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (256, 'Cunégonde', 'Mylène', 'ctootell73@mashable.com', '51 Corscot Center', 'Duantan', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (257, 'Magdalène', 'Göran', 'cbalden74@intel.com', '74151 Park Meadow Pass', 'Caazapá', 'Paraguay');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (258, 'Yáo', 'Irène', 'mgodart75@networksolutions.com', '04 Village Green Crossing', 'Khryashchevka', 'Russia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (259, 'Méline', 'Lauréna', 'pkerfoot76@tumblr.com', '16 Rigney Circle', 'Melissochóri', 'Greece');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (260, 'Océane', 'Adélie', 'atomala77@ycombinator.com', '3 Redwing Hill', 'Bera', 'Bangladesh');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (261, 'Mélissandre', 'Camélia', 'acunio78@creativecommons.org', '5 Tomscot Drive', 'Los Frentones', 'Argentina');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (262, 'Alizée', 'Laïla', 'cshillabeer79@alibaba.com', '28 Utah Hill', 'Bofuer', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (263, 'Mélodie', 'Kallisté', 'iyankov7a@wufoo.com', '3049 Riverside Center', 'Biny Selo', 'Azerbaijan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (264, 'Göran', 'Marlène', 'dhatherleigh7b@stanford.edu', '1253 Pennsylvania Place', 'Imbituva', 'Brazil');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (265, 'Zoé', 'Kévina', 'khains7c@businessinsider.com', '3981 Rowland Way', 'Arrabal', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (266, 'Bérangère', 'Annotés', 'hduncombe7d@issuu.com', '5239 Monterey Plaza', 'Sandy Bay', 'Jamaica');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (267, 'Lóng', 'Maëline', 'plegendre7e@shop-pro.jp', '447 Texas Point', 'Banjar Tengah', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (268, 'Pål', 'Andrée', 'ayeardley7f@mit.edu', '860 Melby Terrace', 'Huntington Beach', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (269, 'Réjane', 'Annotés', 'jsymcock7g@wunderground.com', '3 Parkside Plaza', 'Xiaohe', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (270, 'Néhémie', 'Mélia', 'nyukhnov7h@stanford.edu', '14349 Fieldstone Point', 'Niort', 'France');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (271, 'Märta', 'Mélinda', 'mcowhig7i@amazon.de', '9 Continental Place', 'Varėna', 'Lithuania');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (272, 'Lucrèce', 'Cécile', 'pwhitehair7j@artisteer.com', '599 Monument Crossing', 'Langpas', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (273, 'Maëline', 'Gaïa', 'mlevet7k@networksolutions.com', '68 Haas Junction', 'Asmara', 'Eritrea');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (274, 'Maïlys', 'Loïs', 'eoldman7l@marriott.com', '0544 Crest Line Court', 'Louguan', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (275, 'Méng', 'Clémence', 'rcressor7m@delicious.com', '15 Claremont Pass', 'San Juan Nepomuceno', 'Colombia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (276, 'Fèi', 'Lài', 'gleteurtre7n@usnews.com', '09 Northland Hill', 'Warburton', 'Pakistan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (277, 'Angélique', 'Michèle', 'mpaulsen7o@theatlantic.com', '680 Dakota Road', 'Ryūgasaki', 'Japan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (278, 'Ruì', 'Méng', 'ivasyukhnov7p@blog.com', '228 Daystar Trail', 'Boucherville', 'Canada');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (279, 'Cléopatre', 'Hélène', 'pquantick7q@linkedin.com', '16722 Green Way', 'Izyum', 'Ukraine');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (280, 'Lorène', 'Måns', 'afoukx7r@posterous.com', '3712 Jenifer Plaza', 'Sacramento', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (281, 'Méghane', 'Märta', 'sseamans7s@nytimes.com', '4721 Toban Avenue', 'Tawen Aobao', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (282, 'Anaël', 'Océane', 'chathway7t@miibeian.gov.cn', '6 Monica Lane', 'Chengdong', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (283, 'Maëlann', 'Kallisté', 'glathaye7u@theglobeandmail.com', '50 Shelley Hill', 'Nakama', 'Japan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (284, 'Lyséa', 'Adélaïde', 'rkenward7v@barnesandnoble.com', '532 Elka Place', 'Cagayan', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (285, 'Marie-ève', 'Åslög', 'sdecaroli7w@ft.com', '62077 Saint Paul Avenue', 'Pombal', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (286, 'Pål', 'Loïc', 'trollett7x@lycos.com', '7 Park Meadow Road', 'Eira Nova', 'Portugal');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (287, 'Mylène', 'Yú', 'gjerrim7y@shinystat.com', '0794 Tomscot Way', 'Manaulanan', 'Philippines');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (288, 'Loïc', 'Mén', 'mkeson7z@newsvine.com', '4 Blaine Road', 'Papakura', 'New Zealand');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (289, 'Mélina', 'Léonore', 'labramowitch80@samsung.com', '8504 Westridge Court', 'Mengxi', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (290, 'Hélèna', 'Görel', 'kbrendish81@apache.org', '216 Stang Pass', 'Nagareyama', 'Japan');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (291, 'Chloé', 'Erwéi', 'wtipler82@kickstarter.com', '0 Montana Terrace', 'Suohe', 'China');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (292, 'Marlène', 'Desirée', 'kleeds83@opera.com', '92950 Golden Leaf Court', 'New Haven', 'United States');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (293, 'Faîtes', 'Maëlys', 'kballendine84@ihg.com', '6 Meadow Ridge Park', 'Dhī as Sufāl', 'Yemen');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (294, 'Dù', 'Danièle', 'tgerckens85@i2i.jp', '325 Westport Way', 'La Reforma', 'Mexico');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (295, 'Ruì', 'Cunégonde', 'kshevlin86@dot.gov', '44 Mcguire Parkway', 'Barwałd Średni', 'Poland');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (296, 'Irène', 'Mélina', 'abignall87@salon.com', '90 Hermina Point', 'Měřín', 'Czech Republic');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (297, 'André', 'Eliès', 'valmon88@163.com', '8864 Bonner Trail', 'Barrie', 'Canada');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (298, 'Esbjörn', 'Sòng', 'mashpital89@imageshack.us', '6327 Oak Valley Road', 'Pakapasan Ilir', 'Indonesia');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (299, 'Anaé', 'Estée', 'ebaudone8a@imdb.com', '73 Welch Way', 'Torbeck', 'Haiti');
insert into Customers (id, first_name, last_name, e_mail, address, city, country) values (300, 'Marie-noël', 'Åke', 'mscurlock8b@dedecms.com', '66 Di Loreto Trail', 'Sunja', 'Croatia');
