USE e_commerce;

insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (1, 'LG', 'LG V35 ThinQ', 'Android 8.0, up to Android 9.0', 476.92);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (2, 'Motorola', 'Motorola One (P30 Play)', 'Android 8.1, up to Android 10, Android One', 1112.64);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (3, 'ZTE', 'ZTE U900', 'Android-based OPhone 2.0', 1065.0);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (4, 'Samsung', 'Samsung E2530', 'Feature phone', 1360.61);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (5, 'Sagem', 'Sagem MY X-2', 'Feature phone', 1144.39);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (6, 'Icemobile', 'Icemobile Acqua', 'Feature phone', 772.19);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (7, 'Nokia', 'Nokia 6301', 'Feature phone', 302.9);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (8, 'Samsung', 'Samsung X540', 'Feature phone', 921.62);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (9, 'Nokia', 'Nokia 125', 'Feature phone', 374.95);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (10, 'Lava', 'Lava Iris Atom 2X', 'Android 5.1', 806.66);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (11, 'Huawei', 'Huawei U8850 Vision', 'Android 2.3.4', 1049.09);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (12, 'Apple', 'Apple iPad 2 Wi-Fi + 3G', 'iOS 4, up to iOS 9.3.5', 594.3);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (13, 'Allview', 'Allview A4 Duo', 'Android 4.2', 833.7);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (14, 'HTC', 'HTC Windows Phone 8X CDMA', 'Microsoft Windows Phone 8', 362.25);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (15, 'Nokia', 'Nokia 112', 'Feature phone', 1475.78);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (16, 'Oppo', 'Oppo A92', 'Android 10, ColorOS 7.1', 969.84);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (17, 'Samsung', 'Samsung C520', 'Feature phone', 827.98);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (18, 'Samsung', 'Samsung J210', 'Feature phone', 884.26);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (19, 'Sewon', 'Sewon SG-2000CS', 'Feature phone', 566.76);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (20, 'Samsung', 'Samsung Galaxy Star 2', 'Android 4.4.2', 951.45);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (21, 'Samsung', 'Samsung X610', 'Feature phone', 1493.67);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (22, 'Samsung', 'Samsung E1050', 'Feature phone', 348.78);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (23, 'Telit', 'Telit G82', 'Feature phone', 627.72);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (24, 'LG', 'LG C2200', 'Feature phone', 1480.65);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (25, 'Samsung', 'Samsung M2520 Beat Techno', 'Feature phone', 728.69);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (26, 'Huawei', 'Huawei MediaPad M2 10.0', 'Android 5.1, EMUI 3.1', 974.31);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (27, 'OnePlus', 'OnePlus 5T', 'Android 7.1.1, up to 10, OxygenOS 10.0.0', 1220.82);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (28, 'vivo', 'vivo NEX Dual Display', 'Android 9.0, Funtouch 4.5', 1126.18);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (29, 'Acer', 'Acer Iconia Tab A701', 'Android 4.0', 1187.09);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (30, 'Huawei', 'Huawei Mate 20 X (5G)', 'Android 9.0, EMUI 9.1', 643.01);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (31, 'LG', 'LG L40 Dual D170', 'Android 4.4.2, LG UI 3', 1177.05);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (32, 'Lenovo', 'Lenovo A706', 'Android 4.1', 291.81);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (33, 'Samsung', 'Samsung E2130', 'Feature phone', 1320.15);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (34, 'alcatel', 'alcatel OT-C701', 'Feature phone', 919.78);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (35, 'Micromax', 'Micromax A60', 'Android 2.1', 322.27);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (36, 'BLU', 'BLU Quattro 5.7 HD', 'Android 4.0, up to 4.1', 209.86);
insert into Products (id, mobile_device_brand, mobile_device_model, mobile_device_os, price_€) values (37, 'vivo', 'vivo V5s', 'Android 6, Funtouch 3', 558.06);
